apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-ebpf.fullname" . }}-probe
  labels:
    {{- include "sentinel-ebpf.labels" . | nindent 4 }}
    app.kubernetes.io/component: probe
spec:
  type: ClusterIP
  selector:
    {{- include "sentinel-ebpf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: probe
  ports:
    - name: health
      port: {{ int .Values.config.health.port }}
      targetPort: health
    {{- if and .Values.ui.enabled .Values.config.metrics.enabled }}
    - name: metrics
      port: {{ int .Values.config.metrics.port }}
      targetPort: metrics
    {{- end }}
