lists:
  file_syscalls:
    [
      open,
      openat,
      openat2,
      unlink,
      unlinkat,
      rename,
      renameat,
      chmod,
      chown,
      read,
      write,
      fcntl,
      poll,
      mmap,
      mprotect,
      ioctl,
      fstat,
    ]
  process_syscalls: [execve, fork, set_robust_list]
  network_syscalls:
    [
      socket,
      connect,
      bind,
      listen,
      accept,
      accept4,
      setsockopt,
      getpeername,
      getsockname,
      sendto,
      recvfrom,
      sendmmsg,
    ]
  shell_comms: [bash, sh, zsh]
  noisy_paths: [/proc, /sys, /dev, /run, /var/run, /tmp, /var/log, /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs]

groups:
  file:
    features:
      sensitive_paths: [/etc, /root, /bin, /usr/bin, /sbin, /usr/sbin]
      tmp_paths: [/tmp, /var/tmp]
  process: {}
  network: {}

macros:
  noisy_path: "path startswithin (noisy_paths)"
  filterable_path: "not (syscall_name in (read, write) and path = \"\")"
  shell_proc: "comm in (shell_comms)"

rules:
  - name: capture-file-events
    enabled: true
    group: file
    syscalls: file_syscalls
    condition: "not noisy_path and filterable_path"

  - name: capture-shell-process-events
    enabled: false
    group: process
    syscalls: process_syscalls
    condition: "shell_proc"

  - name: capture-network-events
    enabled: false
    group: network
    syscalls: network_syscalls
